### PR TITLE
Add support for Stock Candles.  Bump version in pom.xml

### PR DESCRIPTION
**Pull request by rcprcp**
Hi, Added support for Stock Candles, and a couple of tests.  I bumped the version to 0.1.1-SNAPSHOT.   Please let me know if you have any questions. 
thanks!

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Thanks a lot

**Comment by oscerd** [comment]
Thanks, I'll release a 0.1.1 soon.

**Comment by oscerd** [comment]
0.1.1 has been released, you should see it on Central in a while @rcprcp

**Comment by rcprcp** [comment]
Thank you.   :)

**Pull request merged**
